name: Build C++ Project

on:
  push:
    branches:
      - main
    paths-ignore:
      - "*.txt"
      - "*.json"
      - "*.md"
      - "*.log"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "*.txt"
      - "*.json"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: install MinGW
        run: |
          choco install mingw --version=8.1.0 -y
          # Import Chocolatey environment variables manually
          Import-Module $env:ChocolateyInstall\helpers\chocolateyProfile.psm1

      - name: compile
        run: .\compile.bat
